config/routes.rb
Rails.application.routes.draw do
  resources :rr_unapproved_records
    
  resources :rr_incoming_records do
    collection do
      get :index
      put :index
    end
  end
  
  resources :reconciled_returns do
    collection do
      get :index
      get :index
    end
  end
  
  get '/reconciled_returns/:id/audit_logs' => 'reconciled_returns#audit_logs'
  get '/rr_incoming_records/:id/audit_logs' => 'rr_incoming_records#audit_logs'
  get 'rr_incoming_file_summary' => 'rr_incoming_records#incoming_file_summary'
end

app/models/reconciled_return.rb
class ReconciledReturn < ActiveRecord::Base
  include ReconciledReturnsHelper
  audited
  
  RET_CODE_TYPE = %w(COMPLETED FAILED)
  attr_accessor :return_code_type
  
  belongs_to :created_user, :foreign_key =>'created_by', :class_name => 'User'
  belongs_to :updated_user, :foreign_key =>'updated_by', :class_name => 'User'
  
  before_validation :set_return_code

  validates_presence_of :txn_type, :return_code_type, :return_code, :settlement_date, :bank_ref_no, :reason
  validates_uniqueness_of :bank_ref_no, :scope => [:txn_type]

  before_save :convert_bank_ref_no_to_upcase
  
  def convert_bank_ref_no_to_upcase
    self.bank_ref_no = self.bank_ref_no.upcase unless self.frozen?
  end
  
  def self.options_for_txn_type
    [['NEFT','NEFT'],['RTGS','RTGS'],['IMPS','IMPS']]
  end

  def set_return_code
    case txn_type
    when 'NEFT'
      if return_code_type == 'COMPLETED'
        self.return_code = '75'
      else
        self.return_code = '99'
      end
    when 'RTGS' 
      if return_code_type == 'COMPLETED'
        self.return_code = 'COM'
      else
        self.return_code = 'REJ'
      end
    when 'IMPS'
      if return_code_type == 'COMPLETED'
        self.return_code = '00'
      else
        self.return_code = '08'
      end
    end
  end
end

app/models/rr_incoming_file.rb
class RrIncomingFile < ActiveRecord::Base  
  has_one :incoming_file, :foreign_key => "file_name", :primary_key => "file_name"
end

app/models/rr_incoming_record.rb
class RrIncomingRecord < ActiveRecord::Base  
  belongs_to :incoming_file_record
  belongs_to :incoming_file, :foreign_key => 'file_name', :primary_key => 'file_name'
end

app/models/rr_unapproved_record.rb
class RrUnapprovedRecord < ActiveRecord::Base
  belongs_to :rr_approvable, :polymorphic => true, :unscoped => true
  RR_TABLES = ['IncomingFile']
end

app/controllers/reconciled_returns_controller.rb
class ReconciledReturnsController < ApplicationController
  authorize_resource
  before_action :authenticate_user!
  before_action :block_inactive_user!
  respond_to :json
  include ApplicationHelper
  include ReconciledReturnsHelper
  
  def index
    reconciled_returns = ReconciledReturn.order("id desc")
    if params[:advanced_search].present? || params[:summary].present?
      reconciled_returns = find_reconciled_returns(params).order("id desc")
    end
    @reconciled_returns_count = reconciled_returns.count(:id)
    @reconciled_returns = reconciled_returns.paginate(:per_page => 10, :page => params[:page]) rescue []
  end
  
  def show
    @reconciled_return = ReconciledReturn.find_by_id(params[:id])
  end

  def new
    @reconciled_return = ReconciledReturn.new
  end

  def create
    @reconciled_return = ReconciledReturn.new(params[:reconciled_return])
    if !@reconciled_return.valid?
      render "new"
    else
      @reconciled_return.created_by = current_user.id
      @reconciled_return.save
      flash[:alert] = 'Reconciled Return successfully created.'
      redirect_to @reconciled_return
    end
  end

  def audit_logs
    @reconciled_return = ReconciledReturn.find(params[:id]) rescue nil
    @audit = @reconciled_return.audits[params[:version_id].to_i] rescue nil
  end

  private

  def reconciled_return_params
    params.require(:reconciled_return).permit(:txn_type, :return_code, :settlement_date, :bank_ref_no, :reason, 
                   :created_by, :updated_by, :updated_by, :last_action, :return_code_type)
  end

end

app/controllers/rr_incoming_records_controller.rb
require 'will_paginate/array'

class RrIncomingRecordsController < ApplicationController
  authorize_resource
  before_filter :authenticate_user!
  before_filter :block_inactive_user!
  respond_to :json, :html
  include SuIncomingRecordsHelper
  include RrIncomingRecordsHelper

  def index
    @incoming_file = IncomingFile.find_by_file_name(params[:file_name]) rescue nil
    records = RrIncomingRecord.joins(:incoming_file_record).where("rr_incoming_records.file_name=? and status=?",params[:file_name],params[:status]).order("rr_incoming_records.id desc")
    records = find_rr_incoming_records(params,records)
    @records_count = records.count(:status)
    @records = records.paginate(:per_page => 10, :page => params[:page]) rescue []
  end

  def show
    @rr_record = RrIncomingRecord.find_by_id(params[:id])
  end

  def audit_logs
    @record = IncomingFileRecord.find(params[:id]) rescue nil
    @audit = @record.audits[params[:version_id].to_i] rescue nil
  end

  def incoming_file_summary
    @summary = RrIncomingFile.find_by_file_name(params[:file_name])    
  end
end

app/controllers/rr_unapproved_records_controller.rb
require 'will_paginate/array'

class RrUnapprovedRecordsController < ApplicationController
  authorize_resource
  before_filter :authenticate_user!
  before_filter :block_inactive_user!
  respond_to :json
  include ApplicationHelper
  include RrUnapprovedRecordsHelper

  def index
    records = filter_records(RrUnapprovedRecord)
    @records = records.paginate(:per_page => 10, :page => params[:page]) rescue []
  end
end

app/helpers/reconciled_returns_helper.rb
module ReconciledReturnsHelper
  def find_reconciled_returns(params)
    reconciled_returns = ReconciledReturn
    reconciled_returns = reconciled_returns.where("bank_ref_no=?", params[:bank_ref_no].upcase) if params[:bank_ref_no].present?
    reconciled_returns
  end
end

app/helpers/rr_incoming_records_helper.rb
module RrIncomingRecordsHelper
  def find_rr_incoming_records(params,records)
    incoming_records = records
    incoming_records = incoming_records.where("overrides is not null") if params[:overrided_flag].present? and params[:overrided_flag] == "true"
    incoming_records = incoming_records.where("overrides is null") if params[:overrided_flag].present? and params[:overrided_flag] == "false"
    incoming_records = incoming_records.where("rr_incoming_records.txn_type=?",params[:txn_type]) if params[:txn_type].present?
    incoming_records = incoming_records.where("rr_incoming_records.bank_ref_no=?",params[:bank_ref_no]) if params[:bank_ref_no].present?
    incoming_records
  end
end

app/helpers/rr_unapproved_records_helper.rb
module RrUnapprovedRecordsHelper
  def filter_records(records)
    result = []
    RrUnapprovedRecord::RR_TABLES.each do |record|
      count = RrUnapprovedRecord.where("rr_approvable_type =?", record).count 
      result << {:record_type => record, :record_count => count}
    end
    result
  end
end

app/views/reconciled_returns/_advanced_search.html.haml
= form_tag '', :method => 'get', :class => 'form-horizontal', :autocomplete=>"off" do
  .control-group
    = label_tag "Bank Ref No", "Bank Ref No", :class => 'control-label'
    = text_field_tag :bank_ref_no, params[:bank_ref_no]
  .form-actions
    = submit_tag "Search", :name => nil, :class => 'btn btn-primary', :id => "adv_search_button"
    = button_tag "Reset", :type => 'button', :value=>'Reset', :class => 'btn', :id => 'reconciled_return_reset'
  = hidden_field_tag :advanced_search, :true

:javascript
  var in_advanced_search = true;

app/views/reconciled_returns/_form.html.haml
= simple_form_for @reconciled_return, :html => {:class=>'form-horizontal', :autocomplete=>"off", :id => "reconciled_return_form"} do |f|
  .control-group
    = f.label ' '
    #msg-error
      = error_message_for(@reconciled_return, :base, :prepend_text => "")
  .form-main
    .control-group
      = f.label :txn_type, "*Txn Type", :class => 'control-label'
      = f.select :txn_type, options_for_select(ReconciledReturn.options_for_txn_type, @reconciled_return.txn_type), :prompt => 'SELECT'
      #msg-error
        = error_message_for(@reconciled_return, :txn_type, :prepend_text => "")
    .control-group
      = f.label :return_code, "*Return Code", :class => 'control-label'
      = f.select :return_code_type, options_for_select(ReconciledReturn::RET_CODE_TYPE), :prompt => 'SELECT'
      #msg-error
        = error_message_for(@reconciled_return, :return_code_type, :prepend_text => "")
    .control-group
      = f.label :settlement_date, "*Settlement Date", :class => 'control-label'
      = f.text_field :settlement_date
      #msg-error
        = error_message_for(@reconciled_return, :settlement_date, :prepend_text => "")
    .control-group
      = f.label :bank_ref_no, "*Bank Ref No", :class => 'control-label'
      = f.text_field :bank_ref_no, :maxlength => 32
      #msg-error
        = error_message_for(@reconciled_return, :bank_ref_no, :prepend_text => "")
    .control-group
      = f.label :reason, "*Reason", :class => 'control-label'
      = f.text_area :reason
      #msg-error
        = error_message_for(@reconciled_return, :reason, :prepend_text => "")

  .form-actions
    - (f.object.new_record?) ? label_name = "Create" : label_name = "Update"
    = f.button "submit" ,:class=>"btn btn-primary", :id => 'submit_reconciled_return', :value => label_name + ' Reconciled Return'
    = link_to :Cancel,'/reconciled_returns', :name => 'cancel', :class=>"cancel btn"

app/views/reconciled_returns/audit_logs.html.haml
.form-horizontal.show_form
  .form-main-with-color{:style=>'background-color: #F1F2F8;'}
    #form-details
      = form_for "audit_logs", :url => "", :method => :get do |f|
        %h3{:style => 'display:inline;'} 
          = "Values at version" 
          = select_tag :version_id, options_for_select(version_ids(@reconciled_return),params[:version_id]), :prompt => 'Select'
          = submit_tag "Show", :name => nil, :class => "btn btn-primary"
      %br
      - unless @audit.nil?
        %table.table.no-border{:style=>"table-layout: fixed; width: 100%"}
          %tr
            %th Field
            %th Old Value
            %th New Value
          %tr
            %td.label 
              = "Change Done By"
            %td.value
              = " " 
            %td.value
              = @audit.user.username
          %tr
            %td.label 
              = "Action"
            %td.value
              = " " 
            %td.value
              = @audit.action
          - @audit.audited_changes.each do |change,value|
            %tr
              %td.label 
                = change
              %td.value
                = old_values(value)
              %td.value
                = new_values(value)

app/views/reconciled_returns/index.html.haml
%br
= link_to 'New Reconciled Return', new_reconciled_return_path
%br
%br
%h1 Listing Reconciled Returns
%h2.collapsible
  Advanced Search
  %span.caret
.collapsible-content
  = render :partial => 'advanced_search'
%br
= "Total Count: #{@reconciled_returns_count}"
%br
= will_paginate @reconciled_returns,:page_links => true
%br
%table.table.table-bordered.table-striped.table-hover
  .thead
    %th{:style=>'text-align:left; background-color: lightblue;'}
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Txn Type
    %th{:style=>'text-align:left; background-color: lightblue;'} 
      Return Code
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Settlement Date
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Bank Ref No

  .tbody
    - @reconciled_returns.each do |reconciled_return|
      %tr
        %td{:style=>'text-align:left;'}
          = link_to 'Show', reconciled_return
        %td{:style=>'text-align:left;'}
          = reconciled_return.txn_type
        %td{:style=>'text-align:left;'}
          = reconciled_return.return_code
        %td{:style=>'text-align:left;'}
          = reconciled_return.settlement_date
        %td{:style=>'text-align:left;'}
          = reconciled_return.bank_ref_no

app/views/reconciled_returns/new.html.haml
%h1 New Reconciled Return

= render 'form'

app/views/reconciled_returns/show.html.haml
.form-horizontal.show_form
  .form-main-with-color{:style=>'background-color: #F1F2F8; height: 600px;'}
    #form-details
      %h3 Reconciled Return Details 
      %br
      %table.table.no-border{:style=>"table-layout: fixed; width: 100%;"}
        %br
        %br
        - if !@reconciled_return.nil?
          %tr
            %td.label Version
            %td.value
              = link_to "#{audit_count(@reconciled_return)}", :controller => :reconciled_returns, :action => :audit_logs, :version_id => audit_count(@reconciled_return), :id => @reconciled_return.id
          %tr
            %td.label Form Errors
            %td.value
              = ' '
            %td#msg-error
              = error_message_for(@reconciled_return, :base, :prepend_text => "")
          %tr
            %td.label Txn Type
            %td.value
              = @reconciled_return.txn_type
            %td#msg-error
              = error_message_for(@reconciled_return, :txn_type, :prepend_text => "")
          %tr
            %td.label Return Code
            %td.value
              = @reconciled_return.return_code
            %td#msg-error
              = error_message_for(@reconciled_return, :return_code, :prepend_text => "")
          %tr
            %td.label Settlement Date
            %td.value
              = @reconciled_return.settlement_date
            %td#msg-error
              = error_message_for(@reconciled_return, :settlement_date, :prepend_text => "")
          %tr
            %td.label Bank Ref No
            %td.value
              = @reconciled_return.bank_ref_no
            %td#msg-error
              = error_message_for(@reconciled_return, :bank_ref_no, :prepend_text => "")

app/views/rr_incoming_records/_advanced_search.html.haml
= form_tag '', :method => 'get', :class => 'form-horizontal', :autocomplete=>"off" do
  .control-group
    = label_tag "Transaction Type", "Transaction Type" , :class => 'control-label'
    = select_tag :txn_type, options_for_select([['NEFT','NEFT'],['IMPS','IMPS'],['RTGS','RTGS']],params[:txn_type]),:prompt => 'ANY'
  .control-group
    = label_tag "Bank Reference No", "Bank Reference No", :class => 'control-label'
    = text_field_tag :bank_ref_no, params[:bank_ref_no]
  = hidden_field_tag :file_name, params[:file_name]
  = hidden_field_tag :status, params[:status]
  = hidden_field_tag :advanced_search, :true
  .form-actions
    = submit_tag "Search", :name => nil, :class => 'btn btn-primary', :id => "adv_search_button"
    = button_tag "Reset", :type => 'button', :value=>'Reset', :class => 'btn', :id => 'adv_search_reset_button'

:javascript
  var in_advanced_search = true;

app/views/rr_incoming_records/audit_logs.html.haml
= render :partial => 'application/audit_logs', :local => {:@record => @record}

app/views/rr_incoming_records/incoming_file_summary.html.haml
.form-horizontal.show_form
  .form-main-with-color{:style=>'background-color: #F1F2F8;  height:630px;'}
    #form-details
      %h3 Reconciled Returns Incoming File
      %br
      %p{:style => 'text-align:left; padding-left:6px; padding-bottom:17px;'}
      - unless @summary.nil?
        %table.table.no-border{:style=>"table-layout: fixed; width: 100%;"}
          %tr
            %td.label File Name
            %td.value
              = @summary.try(:file_name)

app/views/rr_incoming_records/index.html.haml
%br
%h1 Reconciled Returns Incoming Records
%h2.collapsible
  Advanced Search
  %span.caret
.collapsible-content
  = render :partial => 'advanced_search'
%h4
  %br
  &nbsp;
  %br
  = "Total Count: #{@records_count}"
%br
= will_paginate @records, :page_links => true

= simple_form_for :ic_incoming_record, :url => override_records_path, :html => { :method => :get, :class => 'form-horizontal', :autocomplete=>"off", :id => 'update_records', :style=> 'overflow: auto;'} do |f| 
  %table.table.table-bordered.table-striped.table-hover{:style => 'width:100%; border:1px'}
    .thead
      %tr
        %th{:style=>'text-align:left; font-size:12px; background-color: lightblue;'}
        %th{:style=>'text-align:left; background-color: lightblue;'}
          = check_box_tag(:select_all, value = "1", checked = false, options = {})
        %th{:style=>'text-align:left; font-size:12px; background-color: lightblue;'}
          File Name
        %th{:style=>'text-align:left; font-size:12px; background-color: lightblue;'}
          Transaction Type
        %th{:style=>'text-align:left; font-size:12px; background-color: lightblue;'}
          Bank Reference No
        %th{:style=>'text-align:left; font-size:12px; background-color: lightblue;'}
          Settlement Date
        %th{:style=>'text-align:left; font-size:12px; background-color: lightblue;'}
          Attempt No
        %th{:style=>'text-align:left; font-size:12px; background-color: lightblue;'}
          Status
        %th{:style=>'text-align:left; font-size:12px; background-color: lightblue;'}
          Fault Text
        %th{:style=>'text-align:left; font-size:12px; background-color: lightblue;'}
          Fault Bitstream
        %th{:style=>'text-align:left; font-size:12px; background-color: lightblue;'}
          Audit Steps
    .tbody
      - @records.each do |record|
        %tr
          %td{:style=>'text-align:left;'}
            = link_to "show", record
          %td{:style=>'text-align:left;'}
            - if can_select?(record)
              = check_box_tag "record_ids[]", record.incoming_file_record_id, false, class: 'txn_select'
          %td{:style=>'text-align:left;'}
            = record.file_name
          %td{:style=>'text-align:left;'}
            = record.txn_type
          %td{:style=>'text-align:left;'}
            = record.bank_ref_no
          %td{:style=>'text-align:left;'}
            = record.settlement_date.try(:strftime, "%d/%m/%Y %I:%M%p")
          %td{:style=>'text-align:left;'}
            = record.incoming_file_record.attempt_no
          %td{:style=>'text-align:left;'}
            = record.incoming_file_record.status
          %td{:style=>'text-align:left;'}
            - if record.incoming_file_record.fault_code.nil?
              - link_text = "Show Fault Text"
            - else 
              - link_text = record.incoming_file_record.fault_code
            = link_to link_text, "#", :class => 'active-link', :href => "#faultText", data: { fault_reason: record.incoming_file_record.fault_reason, fault_code: record.incoming_file_record.fault_code, fault_subcode: record.incoming_file_record.fault_subcode}
          %td{:style=>'text-align:left;'}
            = link_to "Show Fault Bitstream", "#", :class => 'show_fault_bitstream', :href => "#faultBitstream", data: { fault_bitstream: record.incoming_file_record.fault_bitstream}
          %td{:style=>'text-align:left;'}
            = link_to 'Show', {:controller => 'incoming_file_records', :action => 'audit_steps', :id => record.incoming_file_record_id, :step_name => 'ALL'}
  .form-actions{:style=>"text-align: center;"}
    = hidden_field_tag :file, params[:file_name]
    - if !@incoming_file.nil? and @incoming_file.try(:pending_approval) == 'Y'
      - can_override = (can? :override_records, IncomingFile)
      - can_skip = (can? :skip_records, IncomingFile)
      - can_retry = (can? :approve_restart, IncomingFile)
      - can_reset = (can? :reset, IncomingFile)
      = render :partial => "su_incoming_records/api_buttons", :locals => {:status => params[:status], :can_override => can_override, :can_skip => can_skip, :can_retry => can_retry, :can_reset => can_reset, :file_can_override => @incoming_file.incoming_file_type.try(:can_override), :file_can_skip => @incoming_file.incoming_file_type.try(:can_skip), :file_can_retry => @incoming_file.incoming_file_type.try(:can_retry)}

#faultText.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3 Fault Text
    #error_message{:style => 'color:red'}
  .modal-body{:style => "max-height:450px;"}
    %table.table.no-border
      %tr
        %td.label Fault Code: 
        %td
          %label.fault_code{:style => 'word-wrap: break-word'}
      %tr
        %td.label Fault Reason:
        %td
          %label.fault_reason{:style => 'word-wrap: break-word'}
      %tr
        %td.label Fault Subcode:
        %td
          %label.fault_subcode{:style => 'word-wrap: break-word'}
#faultBitstream.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3 Fault Bitstream
    #error_message{:style => 'color:red'}
  .modal-body{:style => "max-height:450px;"}
    .demo-area
      %button#d_clip_button2.my_clip_button2{"data-clipboard-target" => "fault_bitstream"}
        %b Copy To Clipboard...
    %pre#fault_bitstream{:style => 'word-wrap: break-word'}
      .reply{:style => 'word-wrap: break-word'}

app/views/rr_incoming_records/show.html.haml
.form-horizontal.show_form
  .form-main-with-color{:style=>'background-color: #F1F2F8;  height:630px;'}
    #form-details
      %h3 Reconciled Return Incoming Record
      %br
      %p{:style => 'text-align:left; padding-left:6px; padding-bottom:17px;'}
      %table.table.no-border{:style=>"table-layout: fixed; width: 100%;"}
        %tr
          %td.label Version
          %td.value
            = link_to "#{audit_count(@rr_record.incoming_file_record)}", :controller => :rr_incoming_records, :action => :audit_logs, :version_id => audit_count(@rr_record.incoming_file_record), :id => @rr_record.incoming_file_record_id
        %tr
          %td.label Record Text
          %td.value
            - if @rr_record.incoming_file_record.record_txt.nil?
              .span{:class =>"has-tooltip", "data-toggle" => 'tooltip',"title" => "No Record Text Available for this record", "data-placement" => 'bottom', "data-html" => true}
                Show Record Text
            - else
              = link_to "Show Record Text", "#", :class => 'show_record_text', :href => "#recordText", data: { record_txt: @rr_record.incoming_file_record.record_txt} 

        %tr
          %td.label File Name 
          %td.value
            = @rr_record.file_name
        %tr
          %td.label Transaction Type
          %td.value
            = @rr_record.txn_type
        %tr
          %td.label Bank Reference No
          %td.value
            = @rr_record.bank_ref_no
        %tr
          %td.label Settlement Date
          %td.value
            = @rr_record.settlement_date.try(:strftime, "%d/%m/%Y %I:%M%p")
        %tr
          %td.label Return Code
          %td.value
            = @rr_record.return_code
        %tr
          %td.label Reason
          %td.value
            = @rr_record.reason

#recordText.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3 Record Text
    #error_message{:style => 'color:red'}
  .modal-body{:style => "max-height:450px;"}
    .demo-area
      %button#d_clip_button1.my_clip_button1{"data-clipboard-target" => "record_txt"}
        %b Copy To Clipboard...
    %pre#record_txt{:style => 'word-wrap: break-word'}
      .reply{:style => 'word-wrap: break-word'}

app/views/rr_unapproved_records/index.html.haml
%br
%h1 Reconciled Returns Unapproved Records
%br
- unless @records.nil?
  %br
  = "Total Count: #{@records.count}"
  = will_paginate @records, :page_links => true
  %br
  %table.table.table-bordered.table-striped.table-hover
    .thead
      %th{:style=>'text-align:left; background-color: lightblue;'}
        Record Type
      %th{:style=>'text-align:left; background-color: lightblue;'}
        Record Count
    .tbody
      - @records.each do |record|
        %tr
          %td{:style=>'text-align:left;'}
            = record[:record_type]
          %td{:style=>'text-align:left;'}
            = link_to record[:record_count], {:controller => record[:record_type].tableize, :action => :index, :approval_status => 'U',:sc_service => "RR"}
 